/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ChampionsIndexRouteImport } from './routes/champions.index'
import { Route as ChampionsChampionIdRouteImport } from './routes/champions.$championId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsIndexRoute = ChampionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChampionsRoute,
} as any)
const ChampionsChampionIdRoute = ChampionsChampionIdRouteImport.update({
  id: '/$championId',
  path: '/$championId',
  getParentRoute: () => ChampionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/champions': typeof ChampionsRouteWithChildren
  '/demo': typeof DemoRoute
  '/products': typeof ProductsRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/champions/': typeof ChampionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/products': typeof ProductsRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/champions': typeof ChampionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/champions': typeof ChampionsRouteWithChildren
  '/demo': typeof DemoRoute
  '/products': typeof ProductsRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/champions/': typeof ChampionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/champions'
    | '/demo'
    | '/products'
    | '/champions/$championId'
    | '/champions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/products'
    | '/champions/$championId'
    | '/champions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/champions'
    | '/demo'
    | '/products'
    | '/champions/$championId'
    | '/champions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChampionsRoute: typeof ChampionsRouteWithChildren
  DemoRoute: typeof DemoRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions/': {
      id: '/champions/'
      path: '/'
      fullPath: '/champions/'
      preLoaderRoute: typeof ChampionsIndexRouteImport
      parentRoute: typeof ChampionsRoute
    }
    '/champions/$championId': {
      id: '/champions/$championId'
      path: '/$championId'
      fullPath: '/champions/$championId'
      preLoaderRoute: typeof ChampionsChampionIdRouteImport
      parentRoute: typeof ChampionsRoute
    }
  }
}

interface ChampionsRouteChildren {
  ChampionsChampionIdRoute: typeof ChampionsChampionIdRoute
  ChampionsIndexRoute: typeof ChampionsIndexRoute
}

const ChampionsRouteChildren: ChampionsRouteChildren = {
  ChampionsChampionIdRoute: ChampionsChampionIdRoute,
  ChampionsIndexRoute: ChampionsIndexRoute,
}

const ChampionsRouteWithChildren = ChampionsRoute._addFileChildren(
  ChampionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChampionsRoute: ChampionsRouteWithChildren,
  DemoRoute: DemoRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
